version: 2.1
jobs:
  lint:
    machine:
      image: ubuntu-2204:2024.01.2
    steps:
      - checkout
      - run: make deps
      - run:
          name: Run Linter
          command: make lint
      - run: make docker_build
      - run: make docker_push
  test:
    machine:
      image: ubuntu-2204:2024.01.2
      docker_layer_caching: true
    steps:
      - checkout
      - run: make deps
      - run: make test
workflows:
  basic:
    jobs:
      - lint
      - test:
          requires:
            - lint
